feat: add new fields in MessageEnvelope
edgexfoundry/go-mod-messaging pull request #171
Opened 2022-08-29 07:09 UTC by hahattan

to support north-south messaging implementation

fix #160

Signed-off-by: Chris Hung <chris@iotechsys.com>

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-messaging/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

Add new dependency: https://github.com/edgexfoundry/go-mod-core-contracts
to access the common constants in EdgeX

2022-08-29 11:21 UTC, cloudxxx8 commented on pkg/types/message_envelope.go
> +		ErrorCode:     1,
let's discuss the ErrorCode definition in the Core WG meeting
I thought it could be the same as the http status code

2022-08-29 16:34 UTC, cloudxxx8 commented on pkg/types/message_envelope.go
> +		ErrorCode:     1,
I forgot this has been defined in ADR, so let's follow the ADR statement

2022-08-29 16:34 UTC, cloudxxx8 approved these changes
LGTM

2022-08-29 19:25 UTC, lenny-intel requested changes

2022-08-29 19:25 UTC, lenny-intel commented on go.mod
> +	github.com/edgexfoundry/go-mod-core-contracts/v2 v2.3.0-dev.15
Don't use this just for the single constant. We try not to have this module dependent on any thing else in EdgeX

2022-08-29 19:25 UTC, lenny-intel commented on pkg/types/message_envelope.go
> +	// ErrorCode provides the indication of error.
```suggestion
	// ErrorCode provides the indication of error. '0' indicates no error, '1' indicates error. Additional codes may be added in the future. If non-0, the payload will contain the error.
```

2022-08-29 19:25 UTC, lenny-intel commented on pkg/types/message_envelope.go
>  type MessageEnvelope struct {
The NATS implementation needs to be update to copy these new fields into/from the NATS header 
here: https://github.com/edgexfoundry/go-mod-messaging/blob/e8d1654ba5965c3fb713dc646ae6e642854fae7d/internal/pkg/nats/marshaller.go#L65-L66
and here: 
https://github.com/edgexfoundry/go-mod-messaging/blob/e8d1654ba5965c3fb713dc646ae6e642854fae7d/internal/pkg/nats/marshaller.go#L77-L78

For `QueryParams` you will need to transform the Go map to/from a list of string values containing the Key/Value pairs and use the `.Header.Add("QueryParams", "<key>:<value>")` to add each one 
and `.Header.Values("QueryParams")` to get the list.

2022-08-30 18:03 UTC, lenny-intel requested changes

2022-08-30 18:03 UTC, lenny-intel commented on pkg/types/message_envelope.go
> +	}
ContentType should be set to `text/plain`

2022-08-31 04:56 UTC, hahattan commented on pkg/types/message_envelope.go
> +// NewMessageEnvelopeWithError creates a new MessageEnvelope with ErrorCode set to 1 indicating there's error
these factory functions are good idea.
I'm wondering do we need to validate requestId and coorelationId as they're optional in REST API

2022-08-31 17:49 UTC, lenny-intel commented on pkg/types/message_envelope.go
> +// NewMessageEnvelopeWithError creates a new MessageEnvelope with ErrorCode set to 1 indicating there's error
IMO, RequestId is required since it is needed to match up the response. I am ok with setting the  CoorelationId  if it is empty.

2022-08-31 18:09 UTC, lenny-intel commented on pkg/types/message_envelope.go
> +	if _, err = uuid.Parse(envelope.CorrelationID); err != nil {
Here we could make CorrelationID optional and set it if it is empty.

2022-08-31 18:09 UTC, lenny-intel commented on pkg/types/message_envelope_test.go
> +			}
Adding return avoids need to indent and makes code easier to follow. Also apply this to other tests.
```suggestion
			if tt.expectedError {
				assert.Error(t, err)
				return
			}
			
			assert.Equal(t, testRequestId, envelope.RequestID)
			assert.Equal(t, testCorrelationId, envelope.CorrelationID)
			assert.Equal(t, ApiVersion, envelope.ApiVersion)
			assert.Equal(t, testPayload, string(envelope.Payload))
			assert.Equal(t, ContentTypeJSON, envelope.ContentType)
			assert.Equal(t, 0, envelope.ErrorCode)
			assert.NotNil(t, envelope.QueryParams)
		
```

2022-09-01 16:24 UTC, lenny-intel requested changes

2022-09-01 16:24 UTC, lenny-intel commented on pkg/types/message_envelope.go
> +		envelope.CorrelationID = uuid.NewString()
Should only do this is empty? Invalid UUID should still be an error.

2022-09-01 17:30 UTC, lenny-intel approved these changes
LGTM

2022-09-01 17:30 UTC, merged